apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nginx-argocd
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/fr3dx/kubernetes
    targetRevision: HEAD
    path: kustomize
  destination:
    server: https://kubernetes.default.svc
    namespace: default
