apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: nginx
  name: nginx
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: nginx
    spec:
      initContainers:
      - image: busybox
        name: init-container
        volumeMounts:
        - mountPath: /nginx-data
          name: shared-pod-volume
          command: ["/bin/sh"]
          args: ["-c", "echo 'Development' > /nginx-data/index.html"]
      containers:
      - image: nginx
        name: nginx
      volumes:
      - name: shared-pod-volume
        medium: Memory
---
apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: nginx
  name: nginx
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: nginx
  type: NodePort
